apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    binlog_do_db=sampledb

  slave.cnf: |
    [mysqld]
    server-id=2
    relay_log=relay-bin
