apiVersion: apps/v1
kind: StatefulSet
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: percona/percona-xtradb-cluster:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mypassword"
            - name: CLUSTER_NAME
              value: "k8s-cluster"
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-storage
        namespace: my-namespace
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
