apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "nguyen"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d/mysql.cnf
              subPath: mysql-master.cnf
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - "-c"
                  - |
                    ordinal=$(echo $HOSTNAME | grep -o '[0-9]\+$')
                    if [[ "$ordinal" != "0" ]]; then
                      cp /etc/mysql/conf.d/mysql.cnf /etc/mysql/conf.d/tmp.cnf
                      cp /etc/mysql/conf.d/tmp.cnf /etc/mysql/conf.d/mysql.cnf
                      sed -i "s/server-id=2/server-id=$((ordinal + 1))/" /etc/mysql/conf.d/mysql.cnf
                      rm /etc/mysql/conf.d/tmp.cnf
                    fi

      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: manual
        selector:
          matchLabels:
            app: mysql
            statefulset.kubernetes.io/pod-name: mysql-0
