apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-mysql-0
  namespace: default
  labels:
    app: mysql
  finalizers:
    - kubernetes.io/pvc-protection
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: mysql-pv-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-mysql-1
  namespace: default
  labels:
    app: mysql
  finalizers:
    - kubernetes.io/pvc-protection
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: mysql-pv-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-persistent-storage-mysql-2
  namespace: default
  labels:
    app: mysql
  finalizers:
    - kubernetes.io/pvc-protection
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual
  volumeMode: Filesystem
  volumeName: mysql-pv-2
