apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-master-config: |
    [mysqld]
    server-id=1
    log_bin=mysql-bin
    bind-address=0.0.0.0
  mysql-slave-config: |
    [mysqld]
    server-id=2
    relay_log=mysql-relay
    
