apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: my-namespace
spec:
  ports:
    - port: 3306
  clusterIP: None
  selector:
    app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: my-namespace
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: percona/percona-xtradb-cluster:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "mypassword"
        - name: CLUSTER_NAME
          value: "k8s-cluster"
