apiVersion: v1
kind: Pod
metadata:
  name: mysql
spec:
  containers:
  - name: mysql
    image: mysql:8.0
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "nguyen"
    volumeMounts:
    - name: mysql-config
      mountPath: /etc/mysql/conf.d/mysql.cnf
      subPath: mysql.cnf
    ports:
    - containerPort: 3306
  volumes:
  - name: mysql-config
    configMap:
      name: mysql-config
