apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql  
  template:
    metadata:
      labels:
        app: mysql  
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          volumeMounts:
            - name: mysql-config-volume
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: mysql-config-volume
          configMap:
            name: mysql-config
